services:
  veritas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veritas-app
    env_file: .env
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - test-network
    
    # Restart policy
    restart: unless-stopped
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  test-network:
    external: true
